/**
 * Web-only API surface types. Wire shapes are generated by tygo from
 * `pkg/api/*.go`; see [./types.gen.ts](./types.gen.ts).
 *
 * What lives here vs. there:
 *
 *   - generated: every response struct in `pkg/api`. Edit
 *     the Go side and run `make gen-ts`.
 *   - this file: web-only error envelope, request bodies, and the
 *     handful of wire shapes whose Go counterparts still live as
 *     handler-local structs (HealthResponse, LibraryResponse) that
 *     have not been hoisted into the api package yet.
 */

// Generated `Status` is the episode-status enum (pending / missing /
// …). Re-export under the web-side name so component imports keep
// working — there is no conflict with `lib/status.ts` where `Status`
// names the library-status enum (= generated `ListStatus`).
export type {
  // Add
  AddResult,
  ArtworkShow,
  Candidate,
  CompanionShow,
  EpisodeShow,
  Evidence,
  ExtraItemShow,
  ListResult,
  // List
  ListRow,
  ListStatus,
  MediaShow,
  PosterShow,
  // Resolve
  Resolution,
  SeasonShow,
  SeasonSummary,
  // Show + nested
  Show,
  Status as EpisodeStatus,
  TrashItemShow,
  // Aliases
  UserAliasList,
  UserAliasMutation,
} from './types.gen';

/**
 * `internal/server/auth.writeUnauthorized`-shaped 401 envelope. Also
 * matches the broader REST error envelope used by writeError elsewhere
 * (kind drives the union; message is always populated).
 *
 * Hand-written: the Go side lives in `internal/server/auth` and
 * `internal/server/rest/errors.go`, not in `pkg/api/`.
 */
export interface ApiErrorEnvelope {
  kind: string;
  category?: string;
  message: string;
}

/**
 * Stable kind values the UI dispatches on. Add entries as the auth
 * flow + future error UX needs them.
 */
export const ApiErrorKinds = {
  Unauthorized: 'unauthorized',
  Forbidden: 'forbidden',
  Internal: 'internal',
  Validation: 'validation',
} as const;

/**
 * `GET /api/v1/health` — bearer-exempt by design. Returned for
 * liveness probes; the auth handshake does NOT use it (a 200 here is
 * uninformative about token state).
 *
 * Hand-written: the Go side is `handler_health.go:healthResponse`,
 * a handler-local type that has not been hoisted into
 * `pkg/api/`.
 */
export interface HealthResponse {
  ok: boolean;
  version: string;
  libraryRoot: string;
  uptimeMs: number;
  startedAt: string;
}

/**
 * `GET /api/v1/library` — protected. The auth probe targets this
 * endpoint: a 200 with valid JSON means the bearer is good (or anon
 * mode is in effect); a 401 with the kura error envelope means the
 * bearer is required and we should show the login screen.
 *
 * Hand-written: the Go side is `handler_library.go:libraryResponse`,
 * a handler-local type that has not been hoisted into
 * `pkg/api/`.
 */
export interface LibraryResponse {
  libraryRoot: string;
  seriesCount: number;
  startedAt: string;
  uptimeMs: number;
}

/**
 * `POST /api/v1/resolve` request body. Hand-written: request shapes
 * have not been hoisted into a shared Go package yet.
 */
export interface ResolveRequest {
  terms: string[];
}

/**
 * `POST /api/v1/series` request body. Hand-written: request shapes have
 * not been hoisted into a shared Go package yet. `ref` is a metadata ref
 * (provider:id); `dirname` / `ordering` are optional overrides.
 */
export interface AddRequest {
  ref: string;
  dirname?: string;
  ordering?: string;
}
