// Code generated by tygo. DO NOT EDIT.
// Code generated by tygo from internal/response. DO NOT EDIT.
// Run `make gen-ts` (or `go tool tygo generate -c tools/tygo/tygo.yaml`) to regenerate.

//////////
// source: add.go

/**
 * AddResult is workflow.Add's response. MetadataRef is echoed because
 * the surface caller (CLI / script) often resolved it from text terms
 * rather than passing it directly — the resolved ref is genuinely new
 * info to them. The on-disk Ref is the sanitized directory basename
 * (non-trivial to derive from arbitrary titles); PreferredTitle is the
 * provider's display string. Library root is implicit and dropped.
 */
export interface AddResult {
  metadataRef: string;
  ref: string;
  preferredTitle: string;
}
/**
 * ImportResult is workflow.Import's response. Same shape as AddResult
 * for now; surfaces can render either with the same template.
 */
export type ImportResult = AddResult;

//////////
// source: aliases.go

/**
 * AliasList is the response shape for the series-aliases endpoints
 * (`GET / POST / DELETE /api/v1/series/{ref}/aliases`). Carries the
 * persisted user aliases for the addressed series. TVDB-derived
 * aliases never appear here — they're folded into searchKey at scan
 * time and discarded.
 */
export interface AliasList {
  aliases: string[];
}
/**
 * AliasMutation is the request body for POST + DELETE on the aliases
 * endpoint. Empty / whitespace-only entries are dropped server-side;
 * duplicates collapse into a single change. Unknown aliases on
 * DELETE are no-ops.
 */
export interface AliasMutation {
  aliases: string[];
}

//////////
// source: inbox.go

/**
 * InboxList is workflow.InboxList's response. Path is the (cleaned,
 * NFC) sub-path that was listed; empty means the inbox root itself.
 * When Truncated is true the slice was capped to the caller's Limit
 * (default 500, max 5000). ElidedCount carries how many entries were
 * dropped. Hint contains human-readable suggestions for narrowing the
 * next request.
 */
export interface InboxList {
  path: string;
  entries: InboxEntry[];
  truncated?: boolean;
  elidedCount?: number /* int */;
  hint?: string[];
}
/**
 * InboxEntry is one filesystem entry under the inbox root. Path is
 * forward-slash, NFC, relative to the inbox root. The basename is
 * filepath.Base(Path); the inbox: selector form is "inbox:" + Path —
 * clients can derive both trivially when needed. Size is meaningful
 * only for files; dirs and symlinks emit 0. SymlinkTarget is populated
 * only when Kind == "symlink".
 */
export interface InboxEntry {
  path: string;
  kind: string;
  size?: number /* int64 */;
  mtime?: string;
  symlinkTarget?: string;
}

//////////
// source: job.go

/**
 * JobHandle is the immediate response to a long-tool submission. The
 * client uses JobID to poll JobStatus.
 */
export interface JobHandle {
  jobId: string;
  kind: string;
  series: string;
  startedAt: string;
}
/**
 * JobStatus is the polled view of a tracked job. Built by the
 * surface (e.g. kura_job_status tool, future REST GET /jobs/{id})
 * from a jobs.UntypedJob plus the registry-side error mapping.
 */
export interface JobStatus {
  jobId: string;
  kind: string;
  series: string;
  state: string;
  startedAt: string;
  endedAt?: string;
  progress?: JobProgress;
  result?: unknown;
  error?: JobError;
}
/**
 * JobProgress mirrors progress.Event in the wire format. Lives in
 * response so surfaces can serialize it without importing
 * internal/progress.
 */
export interface JobProgress {
  phase: string;
  status: string;
  message?: string;
  current: number /* int */;
  total: number /* int */;
}
/**
 * JobError is the wire form of a terminal-failed job's cause. Kind is
 * a closed enum (see design/async-job.md § 10); Data carries
 * kind-specific payload.
 */
export interface JobError {
  kind: string;
  message: string;
  data?: { [key: string]: any };
}

//////////
// source: list.go

/**
 * ListStatus is the rolled-up state of one series in the library list.
 * Library-level (vs episode-level Status above): does the series have
 * any tracked metadata, are any episodes missing, are any unaired, etc.
 */
export type ListStatus = 'untracked' | 'complete' | 'incomplete' | 'error';
/**
 * ListStatusUntracked: directory under the library root has no
 * .kura/series.json (Kura does not manage it).
 */
export const ListStatusUntracked: ListStatus = 'untracked';
/**
 * ListStatusComplete: every aired episode has present media, no
 * pending air dates, no missing entries.
 */
export const ListStatusComplete: ListStatus = 'complete';
/**
 * ListStatusIncomplete: at least one aired episode is missing
 * active media, or the series has no episodes at all.
 */
export const ListStatusIncomplete: ListStatus = 'incomplete';
/**
 * ListStatusError: the row could not be computed (parse error,
 * load error). The Error field carries the message.
 */
export const ListStatusError: ListStatus = 'error';
/**
 * ListRow is one row in the library list response. Counts and quality
 * rollups exclude specials (season 0) — they don't factor into series
 * observed state. Resolutions and Sources are the distinct values
 * across non-special episodes with active records, sorted high-
 * quality-first.
 * SeasonsAvailable / EpisodesAvailable count slots populated by an
 * active record. SeasonCount / EpisodeCount are the trackable totals:
 * aired episodes (present + missing) plus any pre-staged future
 * episodes. Pure-pending slots (announced but not aired, no record
 * yet) are EXCLUDED from both totals so the "X / Y" rollup tracks
 * what the user can actually have on disk today. A season counts
 * toward SeasonCount only if it has at least one trackable episode
 * by the same rule. Renderers surface them as "available / total".
 */
export interface ListRow {
  status: ListStatus;
  /**
   * IsAiring is the observed-airing flag, independent of Status. A
   * season counts toward IsAiring when it has at least one
   * future-airdate episode AND the season's first episode has
   * already aired (or airs within 168h). Specials (season 0) are
   * excluded. Computed at row-build time; not persisted to series.json.
   */
  isAiring?: boolean;
  staged?: boolean;
  title: string;
  canonicalTitle?: string;
  seasonsAvailable: number /* int */;
  seasonCount: number /* int */;
  episodesAvailable: number /* int */;
  episodeCount: number /* int */;
  metadataRef?: string;
  resolutions?: string[];
  sources?: string[];
  /**
   * Series-level poster artwork URLs lifted from series.json. Empty
   * strings when the metadata provider had no poster for the series
   * or the row predates poster surfacing — clients should fall back
   * to a placeholder when both are empty.
   */
  posterUrl?: string;
  posterThumbnailUrl?: string;
  lastScanned?: string;
  /**
   * SearchKey is the per-row folded search blob the client feeds
   * into local fuzzy search. Server-side data only — never displayed.
   * Empty when no candidate produces a token (rare; typically a
   * JP-only library that never ran a v3-aware scan).
   */
  searchKey?: string;
  error?: string;
}
/**
 * ListResult is the full library-list response. Rows are sorted by
 * title (lower-cased) and tie-broken on series ref.
 * NextCursor is non-empty when MaxResults capped the page; pass it back
 * as the next request's Cursor to fetch the following page. DataChanged
 * is true when the index changed between pages — clients should re-render
 * from the start of the current page if they care about strict ordering.
 */
export interface ListResult {
  rows: ListRow[];
  nextCursor?: string;
  dataChanged?: boolean;
}

//////////
// source: reconcile.go

/**
 * ReconcilePlan is workflow.PlanReconcile's response. Token/CreatedAt/
 * ExpiresAt are zero when the plan has no changes and no file was
 * persisted.
 */
export interface ReconcilePlan {
  token?: string;
  createdAt?: string;
  expiresAt?: string;
  plan: ReconcilePlanDetail;
}
/**
 * ReconcilePlanDetail is the on-disk plan as seen by callers. Snapshot is
 * omitted from the JSON shape; apply re-reads the on-disk record.
 */
export interface ReconcilePlanDetail {
  series: string;
  changes: ReconcileChange[];
  trashItems?: ReconcileTrashChange[];
  extras?: ReconcileExtraChange[];
}
/**
 * ReconcileTrashChange is one stagedTrash item that will move to
 * .kura/trash/<id>/ on apply. StepIDs lists the step IDs that produced
 * this trash bucket so callers can deterministically map the entry
 * back to plan steps. Source / Resolution / Codec are empty for
 * standalone stagedTrash (no mediainfo probe at stage time); Size and
 * MTime are populated from the on-disk file.
 */
export interface ReconcileTrashChange {
  id: string;
  from: string;
  to: string;
  source?: string;
  resolution?: string;
  codec?: string;
  size?: number /* int64 */;
  mtime?: string;
  companions?: ReconcileMove[];
  stepIds?: string[];
}
/**
 * ReconcileExtraChange is one stagedExtras item that will move into
 * Season N/Extra/[prefix]/<basename> on apply.
 */
export interface ReconcileExtraChange {
  id: string;
  season: number /* int */;
  from: string;
  to: string;
  prefix?: string;
  isDir?: boolean;
  stepIds?: string[];
}
export interface ReconcileChange {
  kind: string;
  episode: string;
  from: string;
  to: string;
  source?: string;
  resolution?: string;
  codec?: string;
  size?: number /* int64 */;
  mtime?: string;
  companions?: ReconcileMove[];
  replaced?: ReconcileReplaced;
  stepIds?: string[];
}
export interface ReconcileMove {
  from: string;
  to: string;
}
export interface ReconcileReplaced {
  from: string;
  to: string;
  source?: string;
  resolution?: string;
  codec?: string;
  size?: number /* int64 */;
  mtime?: string;
  companions?: ReconcileMove[];
  stepIds?: string[];
}
/**
 * ReconcileApply is workflow.ApplyReconcile's response. Populated on
 * both success and failure: AppliedSteps + AppliedStepIDs reflect what
 * the apply actually moved (may be < TotalSteps on partial failure),
 * FailedStep is non-nil when a per-step execution failure aborted the
 * run. Pre-flight failures (plan expired, snapshot stale, claim
 * contention) leave FailedStep nil — those did not touch any step.
 * On partial failure, series.json reflects the pre-apply model — staged
 * records remain staged, active records remain active, no trash drain.
 * Operator's recovery path is `kura reconcile recover` + `kura scan`.
 */
export interface ReconcileApply {
  series: string;
  appliedSteps: number /* int */;
  totalSteps: number /* int */;
  appliedStepIds?: string[];
  failedStep?: FailedReconcileStep;
}
/**
 * FailedReconcileStep names the step whose execution failed during
 * apply. Path / From / To are series-relative slash form when the step
 * targets paths inside the series root; absolute when external.
 */
export interface FailedReconcileStep {
  id: string;
  kind: string;
  ownerKind: string;
  from?: string;
  to?: string;
  path?: string;
  error: string;
}
/**
 * RecoverReconcile is workflow.RecoverReconcile's response. Cleared is
 * true when an in_progress claim was actually removed; PriorHolder
 * identifies who was holding it.
 */
export interface RecoverReconcile {
  ref: string;
  cleared: boolean;
  priorHolder?: { op: string; token?: string; pid: number; host: string; started: string };
}

//////////
// source: reindex.go

/**
 * ReindexResult is the terminal payload of POST /api/v1/library/reindex.
 * Surfaces the row count so the caller can sanity-check the rebuild
 * against expectations without re-fetching the full list.
 */
export interface ReindexResult {
  /**
   * Rows is the total number of rows the rebuild emitted (tracked +
   * untracked + error). Matches `len(index.Rows())` post-write.
   */
  rows: number /* int */;
}

//////////
// source: remove.go

/**
 * Remove is workflow.Remove's response. Caller knew the series ref
 * and whether they passed --purge; only the reclaimed-bytes count is
 * new info.
 */
export interface Remove {
  reclaimedBytes: number /* int64 */;
}

//////////
// source: reset.go

/**
 * ResetResult is workflow.Reset's response. Single-mode (caller passed
 * one Episode) returns just the dropped Record; the episode is echoed
 * from the input. --all mode returns the per-episode list of dropped
 * records so the caller learns what got cleared. Empty Records on
 * --all means there was nothing staged.
 * TrashRemoved and ExtraRemoved list ULIDs of stagedTrash / stagedExtras
 * entries that were dropped — populated when caller passes TrashIDs /
 * ExtraIDs in ResetInput, or when All=true.
 */
export interface ResetResult {
  record?: MediaShow;
  records?: ResetRecord[];
  trashRemoved?: string[];
  extraRemoved?: string[];
}
export interface ResetRecord {
  episode: string;
  record: MediaShow;
}

//////////
// source: resolve.go

/**
 * Resolution is the workflow.Resolve return shape. Outcome is encoded by
 * candidate-list cardinality:
 *   - len(Candidates) == 0 → not found
 *   - len(Candidates) == 1 → unique match
 *   - len(Candidates) >  1 → ambiguous (caller picks)
 * Workflow does not pick. CLI helpers may auto-promote a single candidate
 * or prompt on multi; agents inspect the slice and decide.
 */
export interface Resolution {
  candidates: Candidate[];
}
/**
 * Candidate is one provider match. Fields are flat strings (no NFCString
 * or other textnorm types) so MCP and CLI --json output can serialize
 * uniformly. Add fields here only when at least one surface needs them.
 */
export interface Candidate {
  ref: string;
  preferredTitle: string;
  canonicalTitle?: string;
  year?: number /* int */;
  firstAired?: string;
  originalLanguage?: string;
  originalCountry?: string;
  genres?: string[];
  evidence?: Evidence[];
}
/**
 * Evidence is one term's contribution to a candidate. Surfaces use
 * it for ranking heuristics: which term matched, where in the
 * provider record, and any qualifying annotations (e.g. full_match
 * vs partial_match).
 */
export interface Evidence {
  term: string;
  rank: number /* int */;
  matchSource?: string;
  annotations?: string[];
}

//////////
// source: scan.go

/**
 * ScanStatus is the per-episode outcome of a scan pass.
 */
export type ScanStatus = 'added' | 'updated' | 'unchanged' | 'removed';
export const ScanStatusAdded: ScanStatus = 'added';
export const ScanStatusUpdated: ScanStatus = 'updated';
export const ScanStatusUnchanged: ScanStatus = 'unchanged';
export const ScanStatusRemoved: ScanStatus = 'removed';
/**
 * ScanResult is workflow.Scan's response. Synced is the per-episode
 * reconciliation log (what changed); Skipped is the list of files /
 * directories the scan ignored with reasons; OrphanSlots are episode
 * refs the local model still tracks (because they hold active or
 * staged records) but the provider no longer knows about.
 * ScanResult is workflow.Scan's response. Caller knew the series ref;
 * only the discovered facts (synced episodes, skipped files, orphan
 * slots) are new info.
 */
export interface ScanResult {
  synced: ScannedEpisode[];
  skipped: ScanSkip[];
  orphanSlots: string[];
}
/**
 * ScannedEpisode mirrors what changed for one episode slot during a
 * scan pass: what status (added/updated/...), which episode, and the
 * media facts of the new (or removed) record. Path/Companions are
 * series-relative slash form when the file lives under the series
 * root; paths outside (rare here) remain absolute.
 */
export interface ScannedEpisode {
  status: ScanStatus;
  episode: string;
  source: string;
  resolution?: string;
  path: string;
  companions: string[];
}
/**
 * ScanSkip is one file or directory the scan walked past with an
 * explanation. Codes mirror the scan-internal SkipCode* constants.
 * Source / Resolution / Size are populated when the skipped path is a
 * recognized video file (notably duplicate_slot entries). They give
 * callers enough signal to pick a winner among duplicates without
 * re-walking the filesystem. Other skip codes leave them empty.
 */
export interface ScanSkip {
  path: string;
  code: string;
  reason: string;
  source?: string;
  resolution?: string;
  size?: number /* int64 */;
}
/**
 * Skip code constants. Exported so renderers and MCP schemas can
 * reference them by name.
 */
export const SkipCodeSpecialNumberNotInferred = 'special_number_not_inferred';
/**
 * Skip code constants. Exported so renderers and MCP schemas can
 * reference them by name.
 */
export const SkipCodeEpisodeNumberNotInferred = 'episode_number_not_inferred';
/**
 * Skip code constants. Exported so renderers and MCP schemas can
 * reference them by name.
 */
export const SkipCodeSeasonMismatch = 'season_mismatch';
/**
 * Skip code constants. Exported so renderers and MCP schemas can
 * reference them by name.
 */
export const SkipCodeIgnoredDirectory = 'ignored_directory';
/**
 * Skip code constants. Exported so renderers and MCP schemas can
 * reference them by name.
 */
export const SkipCodeDuplicateSlot = 'duplicate_slot';
/**
 * Skip code constants. Exported so renderers and MCP schemas can
 * reference them by name.
 */
export const SkipCodeMetadataSlotMissing = 'metadata_slot_missing';

//////////
// source: scan_all.go

/**
 * ScanAllResult is the terminal payload of POST /api/v1/library/scan.
 * Aggregates the outcome of fanning per-series scans across the
 * tracked library — total dispatched, succeeded, failed, and the
 * per-series failure detail for any that didn't succeed. Per-series
 * success detail (synced/skipped) is intentionally not aggregated; a
 * caller that needs it issues a single-series scan.
 */
export interface ScanAllResult {
  total: number /* int */;
  succeeded: number /* int */;
  failed: number /* int */;
  failures?: ScanAllFailure[];
}
/**
 * ScanAllFailure carries enough context for a UI or operator to
 * understand which series tripped and why. Kind is the typed error
 * category from internal/errkind so consumers can branch without
 * parsing free-form messages.
 */
export interface ScanAllFailure {
  ref: string;
  kind: string;
  message: string;
}

//////////
// source: show.go

/**
 * Show is workflow.Show's full response: persisted series metadata
 * joined with derived per-episode status and filesystem-issue lists.
 */
export interface Show {
  metadataRef: string;
  ref: string;
  root: string;
  lastScanned?: string;
  preferredTitle: string;
  canonicalTitle?: string;
  status: ListStatus;
  /**
   * IsAiring mirrors ListRow.IsAiring — observed-airing flag
   * independent of Status.
   */
  isAiring?: boolean;
  artwork?: ArtworkShow;
  seasons: SeasonShow[];
  truncated?: boolean;
  truncatedRanges?: string[];
  truncationHint?: string;
  stagedTrash?: TrashItemShow[];
  stagedExtras?: ExtraItemShow[];
}
/**
 * TrashItemShow is one stagedTrash entry queued for removal at the next
 * reconcile_apply. Path is series-relative slash form (the original
 * location). Companions list original locations alongside Path; trash
 * bucket structure is intentionally not exposed on this surface.
 */
export interface TrashItemShow {
  id: string;
  path: string;
  size: number /* int64 */;
  mtime: string;
  addedAt?: string;
  companions?: CompanionShow[];
}
/**
 * ExtraItemShow is one stagedExtras entry queued for placement under
 * Season N/Extra/[Prefix]/<basename> at the next reconcile_apply. Path
 * is absolute because extras can be sourced from anywhere.
 */
export interface ExtraItemShow {
  id: string;
  season: number /* int */;
  path: string;
  prefix?: string;
  isDir: boolean;
  addedAt?: string;
}
/**
 * SeasonShow groups episode rows by season number. Number 0 is specials.
 * Summary always reflects the (possibly filtered) Episodes slice; clients
 * reading filtered responses see filtered summaries, not series-wide totals.
 */
export interface SeasonShow {
  number: number /* int */;
  summary: SeasonSummary;
  episodes?: EpisodeShow[];
}
/**
 * SeasonSummary is the per-season status rollup. Computed over the
 * filter-applied Episodes slice; see SeasonShow doc.
 */
export interface SeasonSummary {
  episodeCount: number /* int */;
  present: number /* int */;
  missing: number /* int */;
  staged: number /* int */;
  stagedReplacement: number /* int */;
  pending: number /* int */;
}
/**
 * EpisodeShow is one episode row with computed status and the active /
 * staged media records (if any). Title fields are provider-supplied
 * display names: PreferredTitle follows KURA_PREFERRED_LANGUAGES with
 * fallback to canonical; CanonicalTitle is the provider's
 * default-language form.
 */
export interface EpisodeShow {
  episode: string;
  aired?: string;
  status: Status;
  preferredTitle?: string;
  canonicalTitle?: string;
  active?: MediaShow;
  staged?: MediaShow;
}
/**
 * ArtworkShow bundles series-level imagery surfaced in show responses.
 * Today only Poster is populated; banner / fanart / clearlogo would
 * add more fields without reshuffling consumers.
 */
export interface ArtworkShow {
  poster?: PosterShow;
}
/**
 * PosterShow is the series-level poster URL.  URL only — kura does not
 * cache image bytes.
 */
export interface PosterShow {
  url: string;
  thumbnailUrl?: string;
  language?: string;
}
/**
 * MediaShow is one media file's display fields for the show view. Paths
 * inside the series root are series-relative slash form; paths outside
 * (e.g. staged-from-inbox files) stay absolute.
 */
export interface MediaShow {
  source: string;
  resolution?: string;
  codec?: string;
  size: number /* int64 */;
  file: string;
  companions: CompanionShow[];
}
export interface CompanionShow {
  path: string;
  role?: string;
  language?: string;
  label?: string;
  size: number /* int64 */;
  mtime: string;
}

//////////
// source: stage.go

/**
 * StageResult is workflow.Stage's response. Stage may queue a mix of
 * episode stages, trash items, and extras in one batch; results surface
 * per-item so the caller (CLI renderer or MCP client) can present a
 * status table.
 * Rows that survived Phase 1 input validation but failed Phase 2 work
 * (mediainfo probe, file vanished mid-flight) appear in Skipped[]. Rows
 * that succeeded appear in Episodes / Trash / Extras with status =
 * "staged" (legacy single-item shape used "replaced" — surface that as
 * status="replaced" for episode rows when the new stage displaced an
 * active record).
 */
export interface StageResult {
  episodes: StageEpisodeResult[];
  trash: StageTrashResult[];
  extras: StageExtraResult[];
  skipped: StageSkip[];
}
/**
 * StageEpisodeResult is one episode item that landed in series.json.
 * Status is one of: "staged" (slot was empty), "replaced" (displaced
 * active record; old file will be trashed on reconcile_apply).
 */
export interface StageEpisodeResult {
  episode: string;
  status: string;
  record: MediaShow;
}
/**
 * StageTrashResult is one trash item queued in stagedTrash[].
 */
export interface StageTrashResult {
  id: string;
  path: string;
}
/**
 * StageExtraResult is one extras item queued in stagedExtras[].
 */
export interface StageExtraResult {
  id: string;
  season: number /* int */;
  path: string;
  prefix?: string;
}
/**
 * StageSkip is one item that survived Phase 1 input validation but
 * failed Phase 2 work. Code is a stable token (probe_failed,
 * source_missing, etc.); Reason is the underlying error message.
 */
export interface StageSkip {
  kind: string;
  path: string;
  code: string;
  reason: string;
}

//////////
// source: status.go
/*
Package response holds the canonical JSON shapes that workflow
functions return. CLI --json output and MCP tool responses share these
shapes. Response files contain shape + simple constructors only; no
derivation logic, no IO. Derivation (computeStatus, computeIssues) lives
in internal/workflow/ as unexported helpers.
*/

/**
 * Status is the observed state of one episode at the time a read
 * workflow ran. Mirrors Product.md § "Episode State (Observed)."
 */
export type Status = 'pending' | 'missing' | 'present' | 'staged' | 'staged_replacement';
/**
 * StatusPending: episode air date is in the future and no media is
 * recorded.
 */
export const StatusPending: Status = 'pending';
/**
 * StatusMissing: episode air date has passed and no media is
 * recorded.
 */
export const StatusMissing: Status = 'missing';
/**
 * StatusPresent: episode has an active media record and the file is
 * reachable on disk.
 */
export const StatusPresent: Status = 'present';
/**
 * StatusStaged: episode has a staged media record awaiting
 * reconcile (no active record present).
 */
export const StatusStaged: Status = 'staged';
/**
 * StatusStagedReplacement: episode has both an active record and a
 * staged record; reconcile will replace the active one.
 */
export const StatusStagedReplacement: Status = 'staged_replacement';

//////////
// source: trash.go

/**
 * TrashList is workflow.TrashList's response. Series are sorted by
 * SeriesRef; entries within each series are sorted by ULID
 * (chronological order since ULIDs are time-ordered).
 */
export interface TrashList {
  series: TrashSeriesEntry[];
  totalEntries: number /* int */;
  totalBytes: number /* int64 */;
}
/**
 * TrashSeriesEntry rolls up trash for one series.
 */
export interface TrashSeriesEntry {
  ref: string;
  entries: TrashEntry[];
  bytes: number /* int64 */;
}
/**
 * TrashEntry mirrors trashfile.Meta in surface-friendly shape.
 */
export interface TrashEntry {
  id: string;
  episode: string;
  trashedAt: string;
  mediaPath: string;
  source?: string;
  resolution?: string;
  size: number /* int64 */;
  companions?: TrashCompanion[];
}
export interface TrashCompanion {
  path: string;
  size: number /* int64 */;
}
/**
 * TrashEmpty is workflow.TrashEmpty's response. Attempts is the total
 * number of trash entries the workflow tried to delete across every
 * targeted series (matched the OlderThan filter); it's >= TotalEntries
 * (entries actually removed). Failures lists per-series errors that
 * stopped one or more deletions; under --all they're best-effort
 * (subsequent series still process), under single-series they cause
 * the workflow to return an error instead. Surfaces enough signal so
 * callers can distinguish "no trash matched the filter" from "every
 * attempt failed" — the latter previously rendered as "Nothing to
 * empty," which was misleading.
 */
export interface TrashEmpty {
  series: TrashSeriesEmpty[];
  totalEntries: number /* int */;
  attempts?: number /* int */;
  reclaimedBytes: number /* int64 */;
  failures?: TrashEmptyFailure[];
}
export interface TrashSeriesEmpty {
  ref: string;
  removed: string[];
  reclaimedBytes: number /* int64 */;
}
/**
 * TrashEmptyFailure is one series whose trash-empty attempt errored.
 * Error carries the wrapped cause's Error() string; structured payload
 * stays in the server log via deps.Logger.Warn.
 */
export interface TrashEmptyFailure {
  ref: string;
  error: string;
}
/**
 * TrashRestore is workflow.TrashRestore's response. Caller passed ref
 * + trash entry ID; the new info is which episode slot the entry came
 * from (recorded at trash time) and the list of paths that got moved
 * back into place. Restored paths are series-relative slash form.
 */
export interface TrashRestore {
  episode: string;
  restored: string[];
}
