/**
 * Web-only API surface types. Wire shapes are generated by tygo from
 * `pkg/api/*.go`; see [./types.gen.ts](./types.gen.ts).
 *
 * What lives here vs. there:
 *
 *   - generated: every response struct in `pkg/api`. Edit
 *     the Go side and run `make gen-ts`.
 *   - this file: web-only error envelope, request bodies, and the
 *     handful of wire shapes whose Go counterparts still live as
 *     handler-local structs (HealthResponse, LibraryResponse) that
 *     have not been hoisted into the api package yet.
 */

// Generated `Status` is the episode-status enum (pending / missing /
// …). Re-export under the web-side name so component imports keep
// working — there is no conflict with `lib/status.ts` where `Status`
// names the library-status enum (= generated `ListStatus`).
export type {
  // Add
  AddResult,
  ArtworkShow,
  Candidate,
  CompanionShow,
  EpisodeShow,
  Evidence,
  ExtraItemShow,
  ListResult,
  // List
  ListRow,
  ListStatus,
  MediaShow,
  PosterShow,
  // Resolve
  Resolution,
  SeasonShow,
  SeasonSummary,
  // Show + nested
  Show,
  Status as EpisodeStatus,
  TrashItemShow,
} from './types.gen';

/**
 * The REST error envelope written by writeError (kind drives the
 * union; message is always populated).
 *
 * Hand-written: the Go side lives in `internal/server/rest/errors.go`,
 * not in `pkg/api/`.
 */
export interface ApiErrorEnvelope {
  kind: string;
  category?: string;
  message: string;
}

/**
 * Stable kind values the UI dispatches on. Add entries as the error
 * UX needs them.
 */
export const ApiErrorKinds = {
  Internal: 'internal',
  Validation: 'validation',
} as const;

/**
 * `GET /api/v1/health` — returned for liveness probes. The boot probe
 * deliberately hits `/api/v1/library` instead, so that a proxy
 * interstitial is distinguishable from a real response.
 *
 * Hand-written: the Go side is `handler_health.go:healthResponse`,
 * a handler-local type that has not been hoisted into
 * `pkg/api/`.
 */
export interface HealthResponse {
  ok: boolean;
  version: string;
  libraryRoot: string;
  uptimeMs: number;
  startedAt: string;
}

/**
 * `GET /api/v1/library` — the boot probe targets this endpoint: a 200
 * with valid JSON means kura answered, while HTML, a redirect, or a
 * 401 means the fronting proxy answered instead.
 *
 * Hand-written: the Go side is `handler_library.go:libraryResponse`,
 * a handler-local type that has not been hoisted into
 * `pkg/api/`.
 */
export interface LibraryResponse {
  libraryRoot: string;
  seriesCount: number;
  startedAt: string;
  uptimeMs: number;
}

/**
 * `POST /api/v1/series/resolve` request body. Hand-written: request shapes
 * have not been hoisted into a shared Go package yet.
 */
export interface ResolveRequest {
  terms: string[];
}

/**
 * `POST /api/v1/series` request body. Hand-written: request shapes have
 * not been hoisted into a shared Go package yet. `ref` is a metadata ref
 * (provider:id); `directory` / `ordering` are optional overrides.
 */
export interface AddRequest {
  ref: string;
  directory?: string;
  ordering?: string;
}
